baseURL = 'https://example.org/'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = 'en'
title = 'Hugo Theme Starter'
description = 'A professional business theme for Hugo'
theme = "hugo-theme-blunix"
uglyURLs = false
disableKinds = ["taxonomy", "term"]
keywords = ["hugo", "theme", "starter", "business", "professional"]
author = "Blunix GmbH"
website = "https://blunix.com"
email = "info@blunix.com"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = false
noClasses = true
