featured_image = 'featured.webp'

[[contact]]
name = "contact@example.com"
icon = "fa-solid fa-envelope"
link = "mailto:contact@example.com"

[[contact]]
name = "+1 234 567 890"
icon = "fa-solid fa-phone"
link = "tel:+1234567890"

[[banner_link]]
name = "+1 234 567 890"
icon = "fa-solid fa-mobile-screen-button"
link = "tel:+1234567890"

[[banner_link]]
name = "contact@example.com"
icon = "fa-solid fa-envelope"
link = "mailto:contact@example.com"

keywords = ["hugo", "theme", "starter", "business", "professional"]
author = "Blunix GmbH"
website = "https://blunix.com"
email = "info@blunix.com"
